# Generated by Django 5.2.5 on 2025-08-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='website_link',
        ),
        migrations.AddField(
            model_name='project',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/hero/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
