# Generated by Django 5.2.5 on 2025-08-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_industry_project_logo_project_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('gallery', 'Gallery'), ('video', 'Video'), ('feature', 'Feature'), ('quote', 'Quote'), ('list', 'List'), ('custom', 'Custom/Other')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/sections/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/sections/videos/')),
                ('extra', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
