# Generated by Django 5.2.5 on 2025-08-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Alternative to uploaded image', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Alternative to uploaded logo', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Alternative to uploaded video', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative to uploaded image', null=True),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='video_url',
            field=models.URLField(blank=True, help_text='Alternative to uploaded video', null=True),
        ),
    ]
