# Generated by Django 5.2.5 on 2025-08-08 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_client_project_date_project_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('gallery', 'Gallery'), ('video', 'Video'), ('features', 'Features Grid'), ('metrics', 'Metrics'), ('quote', 'Quote'), ('list', 'List'), ('custom', 'Custom/Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='SectionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon_text', models.CharField(blank=True, help_text='Emoji or short text icon, e.g. ⚡️', max_length=8)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='projects/sections/features/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='portfolio.projectsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(help_text='Value e.g. 18 hrs, 23x, 4.7x', max_length=50)),
                ('label', models.CharField(help_text='Short label e.g. battery life, faster than …', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Optional extra context', max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='portfolio.projectsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
