# Generated by Django 5.2.5 on 2025-08-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_projectsection_type_sectionfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, help_text='Client or brand. Example: ‘Hasheky Inc.’', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, help_text='Friendly date or year. Example: ‘Aug 2025’ or ‘2024 – Present’.', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload a large hero image (preferred). Use this OR Hero Image URL.', null=True, upload_to='projects/hero/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='OR paste an absolute image URL, e.g. https://... (takes priority if provided)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, help_text='Comma-separated or short label. Example: ‘iOS, Product Design’.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a small logo/icon for the project (shown above the title).', null=True, upload_to='projects/logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo_url',
            field=models.URLField(blank=True, help_text='OR paste a logo URL. If both set, uploaded logo is used.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(help_text='1–2 lines shown under the title. Keep it concise.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='Used in URL. Auto-filled from title. Example: ‘wofa’.', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Project title. Example: ‘WOFA – Work From Anywhere’.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Optional hero video. Use this OR Video URL.', null=True, upload_to='projects/videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='OR paste a video URL.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, help_text='External website or app store URL.', null=True),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='content',
            field=models.TextField(blank=True, help_text='For headings/paragraphs: write text here. For metrics/features: optional title. Example: ‘Built to go places.’', null=True),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='extra',
            field=models.JSONField(blank=True, help_text='Advanced options as JSON. Examples: for list: {"items":["One","Two"]} • for gallery: {"images":["https://...","/media/..."]}', null=True),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image (optional). Use this OR Image URL.', null=True, upload_to='projects/sections/images/'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='image_url',
            field=models.URLField(blank=True, help_text='OR paste an absolute image URL, e.g. https://... (takes priority if provided)', null=True),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order. Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('gallery', 'Gallery'), ('video', 'Video'), ('features', 'Features Grid'), ('metrics', 'Metrics'), ('quote', 'Quote'), ('list', 'List'), ('custom', 'Custom/Other')], help_text='Choose the kind of section you want to add (like Notion blocks).', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video (mp4). Use this OR Video URL.', null=True, upload_to='projects/sections/videos/'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='video_url',
            field=models.URLField(blank=True, help_text='OR paste a video URL (mp4/stream).', null=True),
        ),
        migrations.AlterField(
            model_name='sectionfeature',
            name='description',
            field=models.TextField(blank=True, help_text='One or two lines describing the feature.'),
        ),
        migrations.AlterField(
            model_name='sectionfeature',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Optional icon image (takes priority over emoji)', null=True, upload_to='projects/sections/features/'),
        ),
        migrations.AlterField(
            model_name='sectionfeature',
            name='icon_text',
            field=models.CharField(blank=True, help_text='Emoji or short text icon, e.g. ‘⚡️’ or ‘AI’. Leave empty if using an image.', max_length=8),
        ),
        migrations.AlterField(
            model_name='sectionfeature',
            name='title',
            field=models.CharField(help_text='Feature title e.g. ‘Hyperlocal Discovery’.', max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionmetric',
            name='description',
            field=models.CharField(blank=True, help_text='Optional context shown below label.', max_length=300),
        ),
        migrations.AlterField(
            model_name='sectionmetric',
            name='label',
            field=models.CharField(help_text='Short label e.g. ‘battery life’, ‘faster than M1’.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sectionmetric',
            name='value',
            field=models.CharField(help_text='Value e.g. ‘18 hrs’, ‘23x’, ‘4.7x’.', max_length=50),
        ),
    ]
