# Generated by Django 5.2.5 on 2025-08-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_client_alter_project_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionfeature',
            name='modal_content',
            field=models.TextField(blank=True, help_text='Optional HTML content for the modal body. Use sparingly.'),
        ),
        migrations.AddField(
            model_name='sectionfeature',
            name='modal_description',
            field=models.TextField(blank=True, help_text='Longer rich description for the modal body.'),
        ),
        migrations.AddField(
            model_name='sectionfeature',
            name='modal_image',
            field=models.ImageField(blank=True, help_text='Modal image (optional).', null=True, upload_to='projects/sections/features/modals/'),
        ),
        migrations.AddField(
            model_name='sectionfeature',
            name='modal_title',
            field=models.CharField(blank=True, help_text='Modal title shown when the card is opened. Leave empty to disable modal.', max_length=200),
        ),
        migrations.AddField(
            model_name='sectionfeature',
            name='modal_video_url',
            field=models.URLField(blank=True, help_text='Modal video URL (mp4/stream).', null=True),
        ),
    ]
