# Generated by Django 5.2.5 on 2025-08-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_sectionfeature_modal_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionfeature',
            options={},
        ),
        migrations.AddField(
            model_name='projectsection',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Optional button text.', max_length=100),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='cta_url',
            field=models.URLField(blank=True, help_text='Optional button link.', null=True),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional supporting subheading.', max_length=300),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('accent', 'Accent')], help_text='Visual theme. Defaults to page theme.', max_length=20),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='title',
            field=models.CharField(blank=True, help_text='Optional large heading for this section.', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='content',
            field=models.TextField(blank=True, help_text='Main body text (if any).', null=True),
        ),
        migrations.CreateModel(
            name='SectionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='portfolio.projectsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=150)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='portfolio.projectsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon_text', models.CharField(blank=True, help_text='Emoji or SF Symbol text.', max_length=8)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='projects/sections/tiles/')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='portfolio.projectsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
