# Generated by Django 5.2.5 on 2025-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_sectionfeature_options_projectsection_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionfeature',
            name='background_color',
            field=models.CharField(blank=True, help_text='Tailwind-compatible color or hex, e.g. #111 or bg-gray-900.', max_length=20),
        ),
        migrations.AddField(
            model_name='sectionfeature',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional background image for the card.', null=True, upload_to='projects/sections/features/backgrounds/'),
        ),
        migrations.AddField(
            model_name='sectionfeature',
            name='background_image_url',
            field=models.URLField(blank=True, help_text='Alternative to uploaded background image.', null=True),
        ),
        migrations.AddField(
            model_name='sectionfeature',
            name='style',
            field=models.CharField(choices=[('portrait', 'Portrait (tall)'), ('square', 'Square (default)')], default='square', help_text='Choose portrait to mimic Apple’s tall cards, or square for compact cards.', max_length=20),
        ),
        migrations.AddField(
            model_name='sectionfeature',
            name='text_color',
            field=models.CharField(blank=True, help_text='Hex or CSS color for overlaid title text, default uses theme.', max_length=20),
        ),
    ]
