# Generated by Django 5.2.5 on 2025-08-08 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_sectionfeature_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('gallery', 'Gallery'), ('video', 'Video'), ('features', 'Features Grid'), ('metrics', 'Metrics'), ('media_tabs', 'Media Tabs'), ('quote', 'Quote'), ('list', 'List'), ('custom', 'Custom/Other')], help_text='Choose the kind of section you want to add (like Notion blocks).', max_length=20),
        ),
        migrations.CreateModel(
            name='SectionMediaTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/sections/media_tabs/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_tabs', to='portfolio.projectsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
